global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "192.168.1.231:9093"


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9323']

  - job_name: 'container exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9104']

  - job_name: 'elasticsearch exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9114']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'alertmanagers'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9093']
